CREATE TABLE MyHomeworkDB (
id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(200) NOT NULL,
author_name VARCHAR(150) NOT NULL,
publisher_name VARCHAR(150) NOT NULL,
publish_year year(4) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT NULL
)
